from machine import UART
import time
from machine import Pin
import gc

baudrate=9600
#baudrate=57600

uart = UART(1, baudrate=baudrate,rx=19,tx=21,timeout=10)
uart.write("AT+SAPBR=0,1\r")
time.sleep(1)
print(uart.readline())
print(uart.readline())
uart.write("AT+SAPBR=3,1,\"APN\",\"fast.t-mobile.com\"\r")
time.sleep(1)
print(uart.readline())
print(uart.readline())
uart.write("AT+SAPBR=1,1\r")
time.sleep(1)
print(uart.readline())
print(uart.readline())
uart.write("AT+CMGF=0\r")
time.sleep(1)
print(uart.readline())
print(uart.readline())
uart.write("AT+HTTPINIT\r")
time.sleep(1)
print(uart.readline())
print(uart.readline())
uart.write("AT+HTTPSSL=1\r")
time.sleep(1)
print(uart.readline())
print(uart.readline())
uart.write("AT+HTTPPARA=\"CID\",1\r")
time.sleep(1)
print(uart.readline())
print(uart.readline())
#uart.write("AT+HTTPPARA=\"URL\",\"https://enedig34tr0td.x.pipedream.net\"\r")
uart.write("AT+HTTPPARA=\"URL\",\"https://wolfesneck.farmos.net/farm/sensor/listener/834c74e03901cd1702c0a3060803f767?private_key=bfe468dc77b5530d65319b67cc39cdbc\"\r")
time.sleep(1)
print(uart.readline())
print(uart.readline())
uart.write("AT+HTTPPARA=\"CONTENT\",\"application/json\"\r")
time.sleep(1)
print(uart.readline())
print(uart.readline())
uart.write("AT+HTTPDATA=40,10000\r")
time.sleep(1)
print(uart.readline())
print(uart.readline())
uart.write("{\"location\":238,\"fill\":23\r")
time.sleep(1)
print(uart.readline())
print(uart.readline())
print("sleeping...")
time.sleep(10)
uart.write("AT+HTTPACTION=1\r")
time.sleep(1)
print(uart.readline())
print(uart.readline())
uart.write("AT+HTTPREAD\r")
time.sleep(1)
print(uart.readline())
print(uart.readline())
uart.write("AT+HTTPTERM\r")
time.sleep(1)
print(uart.readline())
print(uart.readline())
